#!/bin/bash

cd /home/boat/crowdcountingdarknet
./darknet detector demo /home/boat/crowdcountingdarknet/cfg/coco.data /home/boat/crowdcountingdarknet/cfg/yolov3.cfg /home/boat/crowdcountingdarknet/weights/yolov3.weights /home/boat/Videos/topdown.avi
