#!/bin/bash

cd /home/autoware/crowdcountingdarknet
./darknet detector demo /home/hecate/crowdcountingdarknet/cfg/coco.data /home/autoware/crowdcountingdarknet/cfg/yolov3.cfg /home/autoware/crowdcountingdarknet/weights/yolov3.weights /home/autoware/Videos/topdown.avi
